"""market trades and book snapshots

Revision ID: 3f94d44a125e
Revises: 50a176ca2955
Create Date: 2026-09-26 10:59:19.164745
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3f94d44a125e'
down_revision: Union[str, None] = '50a176ca2955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_book_snapshots',
    sa.Column('token_id', sa.String(length=100), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('best_bid', sa.Float(), nullable=True),
    sa.Column('best_ask', sa.Float(), nullable=True),
    sa.Column('bids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('token_id', 'ts')
    )
    op.create_table('market_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.String(length=100), nullable=False),
    sa.Column('condition_id', sa.String(length=100), nullable=False),
    sa.Column('outcome_index', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('tx_hash', sa.String(length=80), nullable=False),
    sa.Column('wallet', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash', 'token_id', 'wallet', 'side', 'price', 'size', name='uq_market_trade')
    )
    op.create_index(op.f('ix_market_trades_condition_id'), 'market_trades', ['condition_id'], unique=False)
    op.create_index(op.f('ix_market_trades_token_id'), 'market_trades', ['token_id'], unique=False)
    op.create_index(op.f('ix_market_trades_ts'), 'market_trades', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_trades_ts'), table_name='market_trades')
    op.drop_index(op.f('ix_market_trades_token_id'), table_name='market_trades')
    op.drop_index(op.f('ix_market_trades_condition_id'), table_name='market_trades')
    op.drop_table('market_trades')
    op.drop_table('market_book_snapshots')
    # ### end Alembic commands ###
