"""users roles activity log

Revision ID: 8d64d59a2940
Revises: f3e017071b76
Create Date: 2026-09-26 10:14:34.347957
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8d64d59a2940'
down_revision: Union[str, None] = 'f3e017071b76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('activity_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('path', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_log_action'), 'activity_log', ['action'], unique=False)
    op.create_index(op.f('ix_activity_log_ts'), 'activity_log', ['ts'], unique=False)
    op.create_index(op.f('ix_activity_log_user_id'), 'activity_log', ['user_id'], unique=False)
    op.add_column('house_bets', sa.Column('taker_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_house_bets_taker_id'), 'house_bets', ['taker_id'], unique=False)
    op.create_foreign_key(None, 'house_bets', 'users', ['taker_id'], ['id'], ondelete='SET NULL')
    op.add_column('house_markets', sa.Column('maker_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('house_markets_race_id_athlete_id_kind_key'), 'house_markets', type_='unique')
    op.create_index(op.f('ix_house_markets_maker_id'), 'house_markets', ['maker_id'], unique=False)
    op.create_unique_constraint('uq_house_market_maker', 'house_markets', ['race_id', 'athlete_id', 'kind', 'maker_id'])
    op.create_foreign_key(None, 'house_markets', 'users', ['maker_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'house_markets', type_='foreignkey')
    op.drop_constraint('uq_house_market_maker', 'house_markets', type_='unique')
    op.drop_index(op.f('ix_house_markets_maker_id'), table_name='house_markets')
    op.create_unique_constraint(op.f('house_markets_race_id_athlete_id_kind_key'), 'house_markets', ['race_id', 'athlete_id', 'kind'], postgresql_nulls_not_distinct=False)
    op.drop_column('house_markets', 'maker_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'house_bets', type_='foreignkey')
    op.drop_index(op.f('ix_house_bets_taker_id'), table_name='house_bets')
    op.drop_column('house_bets', 'taker_id')
    op.drop_index(op.f('ix_activity_log_user_id'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_ts'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_action'), table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_table('users')
    # ### end Alembic commands ###
