"""polymarket alignment

Revision ID: d84cd5aa7ce4
Revises: 8d64d59a2940
Create Date: 2026-09-26 10:27:43.579045
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd84cd5aa7ce4'
down_revision: Union[str, None] = '8d64d59a2940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('house_markets', sa.Column('market_link_id', sa.Integer(), nullable=True))
    op.add_column('house_markets', sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('house_markets', 'race_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('house_markets', 'athlete_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_house_markets_market_link_id'), 'house_markets', ['market_link_id'], unique=False)
    op.create_foreign_key(None, 'house_markets', 'market_links', ['market_link_id'], ['id'], ondelete='SET NULL')
    op.add_column('market_links', sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('market_links', sa.Column('event_slug', sa.String(length=300), nullable=True))
    op.add_column('market_links', sa.Column('event_title', sa.Text(), nullable=True))
    op.add_column('market_links', sa.Column('group_title', sa.String(length=200), nullable=True))
    op.add_column('market_links', sa.Column('last_bid', sa.Float(), nullable=True))
    op.add_column('market_links', sa.Column('last_ask', sa.Float(), nullable=True))
    op.add_column('market_links', sa.Column('last_price', sa.Float(), nullable=True))
    op.add_column('market_links', sa.Column('volume', sa.Float(), nullable=True))
    op.add_column('market_links', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('market_links', sa.Column('closed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('market_links', sa.Column('resolved_yes', sa.Boolean(), nullable=True))
    op.add_column('market_links', sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('market_links', 'athlete_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_market_links_event_slug'), 'market_links', ['event_slug'], unique=False)
    op.add_column('standings_predictions', sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standings_predictions', 'extra')
    op.drop_index(op.f('ix_market_links_event_slug'), table_name='market_links')
    op.alter_column('market_links', 'athlete_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('market_links', 'synced_at')
    op.drop_column('market_links', 'resolved_yes')
    op.drop_column('market_links', 'closed')
    op.drop_column('market_links', 'end_date')
    op.drop_column('market_links', 'volume')
    op.drop_column('market_links', 'last_price')
    op.drop_column('market_links', 'last_ask')
    op.drop_column('market_links', 'last_bid')
    op.drop_column('market_links', 'group_title')
    op.drop_column('market_links', 'event_title')
    op.drop_column('market_links', 'event_slug')
    op.drop_column('market_links', 'params')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'house_markets', type_='foreignkey')
    op.drop_index(op.f('ix_house_markets_market_link_id'), table_name='house_markets')
    op.alter_column('house_markets', 'athlete_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('house_markets', 'race_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('house_markets', 'params')
    op.drop_column('house_markets', 'market_link_id')
    # ### end Alembic commands ###
