"""market price history

Revision ID: 50a176ca2955
Revises: 8c46493d7cda
Create Date: 2026-09-26 10:44:35.978421
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '50a176ca2955'
down_revision: Union[str, None] = '8c46493d7cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_price_history',
    sa.Column('token_id', sa.String(length=100), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('token_id', 'ts')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_price_history')
    # ### end Alembic commands ###
