"""market links and orders

Revision ID: 66d4b92ba307
Revises: 1983462a0695
Create Date: 2026-09-26 03:09:34.901494
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '66d4b92ba307'
down_revision: Union[str, None] = '1983462a0695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('exchange', sa.String(length=20), server_default='polymarket', nullable=False),
    sa.Column('market_slug', sa.String(length=300), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('condition_id', sa.String(length=80), nullable=True),
    sa.Column('token_id', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.String(length=200), nullable=False),
    sa.Column('neg_risk', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('tick_size', sa.Float(), nullable=True),
    sa.Column('min_size', sa.Float(), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('prediction', sa.String(length=30), nullable=False),
    sa.Column('invert', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_links_token_id'), 'market_links', ['token_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('exchange', sa.String(length=20), server_default='polymarket', nullable=False),
    sa.Column('market_link_id', sa.Integer(), nullable=True),
    sa.Column('token_id', sa.String(length=100), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('order_type', sa.String(length=8), server_default='GTC', nullable=False),
    sa.Column('post_only', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('exchange_order_id', sa.String(length=100), nullable=True),
    sa.Column('model_prob', sa.Float(), nullable=True),
    sa.Column('best_bid', sa.Float(), nullable=True),
    sa.Column('best_ask', sa.Float(), nullable=True),
    sa.Column('model_run_id', sa.Integer(), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['market_link_id'], ['market_links.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_index(op.f('ix_market_links_token_id'), table_name='market_links')
    op.drop_table('market_links')
    # ### end Alembic commands ###
