"""laps track profiles round extra

Revision ID: f3e017071b76
Revises: 0e47bb766d0b
Create Date: 2026-09-26 09:58:28.643499
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f3e017071b76'
down_revision: Union[str, None] = '0e47bb766d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_profiles',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_track_profiles_venue_id'), 'track_profiles', ['venue_id'], unique=False)
    op.create_table('laps',
    sa.Column('result_id', sa.BigInteger(), nullable=False),
    sa.Column('lap', sa.Integer(), nullable=False),
    sa.Column('lap_time_ms', sa.BigInteger(), nullable=True),
    sa.Column('s1_ms', sa.BigInteger(), nullable=True),
    sa.Column('s2_ms', sa.BigInteger(), nullable=True),
    sa.Column('s3_ms', sa.BigInteger(), nullable=True),
    sa.Column('speed_i1', sa.Float(), nullable=True),
    sa.Column('speed_i2', sa.Float(), nullable=True),
    sa.Column('speed_fl', sa.Float(), nullable=True),
    sa.Column('speed_st', sa.Float(), nullable=True),
    sa.Column('compound', sa.String(length=16), nullable=True),
    sa.Column('tyre_life', sa.Float(), nullable=True),
    sa.Column('stint', sa.Integer(), nullable=True),
    sa.Column('pit_in', sa.Boolean(), nullable=True),
    sa.Column('pit_out', sa.Boolean(), nullable=True),
    sa.Column('track_status', sa.String(length=16), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('is_accurate', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id', 'lap')
    )
    op.add_column('rounds', sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rounds', 'extra')
    op.drop_table('laps')
    op.drop_index(op.f('ix_track_profiles_venue_id'), table_name='track_profiles')
    op.drop_table('track_profiles')
    # ### end Alembic commands ###
