"""house market uniqueness per mirrored link

Revision ID: 8c46493d7cda
Revises: d84cd5aa7ce4
Create Date: 2026-09-26 10:32:56.847810
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8c46493d7cda'
down_revision: Union[str, None] = 'd84cd5aa7ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_house_market_maker'), 'house_markets', type_='unique')
    op.create_unique_constraint('uq_house_market_maker', 'house_markets', ['race_id', 'athlete_id', 'kind', 'maker_id', 'market_link_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_house_market_maker', 'house_markets', type_='unique')
    op.create_unique_constraint(op.f('uq_house_market_maker'), 'house_markets', ['race_id', 'athlete_id', 'kind', 'maker_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
