"""house markets and bets

Revision ID: 0e47bb766d0b
Revises: 66d4b92ba307
Create Date: 2026-09-26 03:27:08.353222
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0e47bb766d0b'
down_revision: Union[str, None] = '66d4b92ba307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house_markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=True),
    sa.Column('fair_prob', sa.Float(), nullable=False),
    sa.Column('fair_source', sa.String(length=20), server_default='model', nullable=False),
    sa.Column('spread', sa.Float(), nullable=False),
    sa.Column('yes_price', sa.Float(), nullable=True),
    sa.Column('no_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=10), server_default='open', nullable=False),
    sa.Column('outcome', sa.Boolean(), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settle_note', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'athlete_id', 'kind')
    )
    op.create_table('house_bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('counterparty', sa.String(length=120), nullable=False),
    sa.Column('side', sa.String(length=3), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('payout', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='open', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['house_markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_house_bets_market_id'), 'house_bets', ['market_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_house_bets_market_id'), table_name='house_bets')
    op.drop_table('house_bets')
    op.drop_table('house_markets')
    # ### end Alembic commands ###
