"""Write sweeps/global-multi-sport.toml: the results model (models/model_global.py) on every sport that has
[model] schema hooks and results history, one walk-forward job per sport x season x settings combo.

    python scripts/make_global_sweep.py [--sports f1 motogp nascar] [--seasons 2026 2025 2024 2023] [--out PATH]

The grid is one-at-a-time around the defaults, then a factorial on the three settings that move the most
(half_life_days x prior_weight x noise), then uncertainty x group_weight x dnf. Duplicates collapse by job id when
the queue loads. Season 1 of `--seasons` is the target; the rest are held out (search-report labels a combo
robust only if it beats the baseline in all of them). The default-settings job runs at 3 seeds per season so
search-report measures its noise floor.
"""

import argparse
import itertools
import json
from pathlib import Path

OFAT = dict(half_life_days=[90, 120, 180, 360, 540, 1000], prior_weight=[1, 2, 5, 8], noise=[0.5, 0.65, 1.0, 1.2],
            uncertainty=[0, 0.25, 0.75, 1.0], group_weight=[0.25, 0.5, 1.0], dnf=[False])
CORE = dict(half_life_days=[120, 240, 480], prior_weight=[2, 3, 6], noise=[0.65, 0.8, 1.0])
EXTRA = dict(uncertainty=[0.25, 0.5, 0.75], group_weight=[0, 0.5, 1.0], dnf=[True, False])
EVENTS = dict(f1=24, motogp=20, nascar=40)          # events a season: the report's concentration stats


def combos():
    out = [{k: v} for k, vs in OFAT.items() for v in vs]
    for grid in (CORE, EXTRA):
        out += [dict(zip(grid, vals)) for vals in itertools.product(*grid.values())]
    return out


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--sports", nargs="+", default=["f1", "motogp", "nascar"])
    ap.add_argument("--seasons", nargs="+", type=int, default=[2026, 2025, 2024, 2023])
    ap.add_argument("--out", default=str(Path(__file__).resolve().parents[1] / "sweeps" / "global-multi-sport.toml"))
    ap.add_argument("--name", default="global-multi-sport")
    ap.add_argument("--hours", type=float, default=4.0)
    a = ap.parse_args(argv)
    seen, lines = set(), []
    for sport in a.sports:
        for year in a.seasons:
            base = dict(sport=sport, model="global", year=year)
            jobs = [dict(base, replicates=3, note="default settings, 3 seeds: the noise floor")]
            jobs += [dict(base, **c) for c in combos()]
            for j in jobs:
                key = json.dumps(j, sort_keys=True)
                if key not in seen:
                    seen.add(key)
                    lines.append("  {" + ", ".join(f"{k} = {json.dumps(v)}" for k, v in j.items()) + "},")
    text = ["# Generated by scripts/make_global_sweep.py; edit the generator, not this file.",
            "job = [", *lines, "]", "",
            f'[search]\nname = "{a.name}"\nparallel = 1\nhours = {a.hours}\ngrace_minutes = 10', ""]
    for sport in a.sports:
        text += [f"[report.{sport}]", f"target = {a.seasons[0]}", f"holdout = {json.dumps(a.seasons[1:])}",
                 f"season_events = {EVENTS.get(sport, 20)}", ""]
    Path(a.out).write_text("\n".join(text))
    print(f"{len(lines)} jobs -> {a.out}")


if __name__ == "__main__":
    main()
