"""Write sweeps/global-multi-sport.toml: the results model (models/model_global.py) on every sport that has
[model] schema hooks and results history, one walk-forward job per sport x season x settings combo.

    python scripts/make_global_sweep.py [--sports f1 motogp nascar] [--seasons 2026 2025 2024 2023] [--out PATH]

The grid is one-at-a-time around the defaults, then a factorial on the three settings that move the most
(half_life_days x prior_weight x noise), then uncertainty x group_weight x dnf. Duplicates collapse by job id when
the queue loads. Season 1 of `--seasons` is the target; the rest are held out (search-report labels a combo
robust only if it beats the baseline in all of them). The default-settings job runs at 3 seeds per season so
search-report measures its noise floor.

    python scripts/make_global_sweep.py --confirm data/runs/search/global-multi-sport

Stage 2: reads each sport's candidates.toml from a finished, reported search and writes the queue that re-runs those
combos, and the default settings, at the report's `confirm_sims` in every season (sweeps/global-multi-sport-confirm.toml,
the same search name, so one search-report reads both stages).
"""

import argparse
import itertools
import json
import tomllib
from pathlib import Path

from racinglines.pipelines import search_report as SRR

OFAT = dict(half_life_days=[90, 120, 180, 360, 540, 1000], prior_weight=[1, 2, 5, 8], noise=[0.5, 0.65, 1.0, 1.2],
            uncertainty=[0, 0.25, 0.75, 1.0], group_weight=[0.25, 0.5, 1.0], dnf=[False])
CORE = dict(half_life_days=[120, 240, 480], prior_weight=[2, 3, 6], noise=[0.65, 0.8, 1.0])
EXTRA = dict(uncertainty=[0.25, 0.5, 0.75], group_weight=[0, 0.5, 1.0], dnf=[True, False])
EVENTS = dict(f1=24, motogp=20, nascar=40)          # events a season: the report's concentration stats
CANDIDATE_META = {"id", "name", "year", "strategy", "why", "sport", "model", "venue"}   # the rest are settings


def combos():
    out = [{k: v} for k, vs in OFAT.items() for v in vs]
    for grid in (CORE, EXTRA):
        out += [dict(zip(grid, vals)) for vals in itertools.product(*grid.values())]
    return out


def confirm_combos(root, sport):
    """The distinct settings of a sport's candidates (several market kinds share a combo), in report order."""
    cands = tomllib.loads((Path(root) / f"{sport}-global" / "candidates.toml").read_text()).get("candidate", [])
    return [json.loads(k) for k in dict.fromkeys(
        json.dumps({k: v for k, v in c.items() if k not in CANDIDATE_META}, sort_keys=True) for c in cands)]


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--sports", nargs="+", default=["f1", "motogp", "nascar"])
    ap.add_argument("--seasons", nargs="+", type=int, default=[2026, 2025, 2024, 2023])
    ap.add_argument("--out", help="default: sweeps/global-multi-sport.toml (sweeps/global-multi-sport-confirm.toml with --confirm)")
    ap.add_argument("--name", default="global-multi-sport")
    ap.add_argument("--hours", type=float, default=4.0)
    ap.add_argument("--parallel", type=int, default=3,
                    help="jobs at once: each takes ~2 s of CPU but the runner polls every 15 s, so 3 is still light")
    ap.add_argument("--confirm", metavar="DIR", help="stage 2: the finished search's folder (candidates.toml per sport)")
    a = ap.parse_args(argv)
    sweeps = Path(__file__).resolve().parents[1] / "sweeps"
    out = a.out or str(sweeps / ("global-multi-sport-confirm.toml" if a.confirm else "global-multi-sport.toml"))
    sims = SRR.SPORT_DEFAULTS["global"]["confirm_sims"]
    seen, lines = set(), []
    for sport in a.sports:
        for year in a.seasons:
            base = dict(sport=sport, model="global", year=year)
            if a.confirm:
                jobs = [dict(base, sims=sims, replicates=3, note="confirmation baseline, 3 seeds: the noise floor at this fidelity")]
                jobs += [dict(base, sims=sims, **c) for c in confirm_combos(a.confirm, sport)]
            else:
                jobs = [dict(base, replicates=3, note="default settings, 3 seeds: the noise floor")]
                jobs += [dict(base, **c) for c in combos()]
            for j in jobs:
                key = json.dumps(j, sort_keys=True)
                if key not in seen:
                    seen.add(key)
                    lines.append("  {" + ", ".join(f"{k} = {json.dumps(v)}" for k, v in j.items()) + "},")
    text = ["# Generated by scripts/make_global_sweep.py; edit the generator, not this file.",
            "job = [", *lines, "]", "",
            f'[search]\nname = "{a.name}"\nparallel = {a.parallel}\nhours = {a.hours}\ngrace_minutes = 10', ""]
    for sport in a.sports:
        text += [f"[report.{sport}]", f"target = {a.seasons[0]}", f"holdout = {json.dumps(a.seasons[1:])}",
                 f"season_events = {EVENTS.get(sport, 20)}", ""]
    Path(out).write_text("\n".join(text))
    print(f"{len(lines)} jobs -> {out}")


if __name__ == "__main__":
    main()
